<!-- <div class="entry-edit">
    <button class="scalable add" style="float: right;" onclick="addItemSelect()" type="button"><span>Add Selected Products(s) to Order</span></button>
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <?php echo $this->getChildHtml('product_grid') ?>
</div>
</div> -->
<!-- <script type="text/javascript">
     function addItemSelect(){
        var action = document.getElementById('order_create_search_grid_massaction-select').selectedIndex = '1';
        order_create_search_grid_massactionJsObject.apply();
     };
</script> -->