<?php $methods = $this->getPayemntMethodTitle() ?>
<?php $methodCode = $this->getCode() ?>
<div id="order-billing_method" class="box-left payments" style="height: 200px;">
    <div>
        <div class="entry-edit">
            <button style="float: right;" type="button"  onclick="biilingMethodSave()"  name="billing" class="scalable task">Save</button>
            <div class="entry-edit-head">
                <div style="float: right;"></div>
                <h4 class="fieldset-legend head-payment-method icon-head">Payment Method</h4>
            </div>
            <div class="fieldset">
                <div id="order-billing_method_form">
                    <dl class="payment-methods">
                        <?php foreach($methods as $code => $method): ?>
                        <dt>
                            <input value="<?php echo $code ?>" type="radio" <?php if($methodCode == $code): ?>checked<?php endif; ?> name="method[payment]"
                                title="Credit Card (saved)" >

                            <label for="p_method"><?php echo $method->getTitle() ?></label>
                        </dt>
                        <?php endforeach; ?>
                    </dl>
                </div>

            </div>
        </div>
    </div>
</div>