<?php $order = $this->getOrder() ?>
<div class="box-left">
            <!--Payment Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method">Payment Information</h4>
            </div>
            <fieldset>
                <?php echo $order->getBillingMethod() ?>

                <div>Order was placed using INR</div>
            </fieldset>
        </div>
    </div>