<?php $customer = $this->getOrder()->getCustomer() ?>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account">Account Information</h4>
            <div class="tools"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label>Customer Name</label></td>
                            <td class="value">
                                <?php echo $customer->getFirstname() ?> <?php echo $customer->getLastname() ?> <?php echo $customer->getMiddlename() ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label>Email</label></td>
                            <td class="value"><a ><strong><?php echo $customer->getEmail() ?></strong></a></td>
                        </tr>
                        <tr>
                            <td class="label"><label>Middle Name/Initial</label></td>
                            <td class="value"><strong><?php echo $customer->getMiddlename() ?></strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>