<?php $order = $this->getOrder() ?>
<div class="box-left" >
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account">Order # <?php echo $order->getId() ?></h4>
    </div>
    <div class="fieldset" style="height: 80px;">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label>Order Date</label></td>
                    <td class="value"><strong><?php echo $order->getCreatedAt() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label>Order Status</label></td>
                    <td class="value"><strong><span id="order_status"><?php echo $order->getStatus() ?></span></strong></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>