<?php $subTotal = $this->getOrder()->getSubTotal() ?>
<?php $grandTotal = $this->getTotal() ?>
<?php $shippingAmmount = $this->getShippingAmount() ?>
<div class="box-right entry-edit">
    <div class="entry-edit-head">
        <h4>Order Totals</h4>
    </div>
    <div id="order-totals" class="order-totals">
        <div>
            <table cellspacing="0" cellpadding="8" width="100%">
                <tbody>
                    <tr>
                        <td class="a-right" colspan="1">
                            Subtotal </td>
                        <td class="a-right">
                            <span class="price">₹<?php echo $subTotal ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="a-right" colspan="1">
                            Shipping &amp; Handling (Flat Rate - Fixed) </td>
                        <td class="a-right">
                            <span class="price">₹<?php echo $shippingAmmount ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="a-right" colspan="1">
                            <strong>Grand Total</strong>
                        </td>
                        <td class="a-right">
                            <strong><span class="price">₹<?php echo $grandTotal ?></span></strong>
                        </td>
                    </tr>
                </tbody>
            </table>


        </div>
    </div>
</div>