
<form id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <div   style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('search') ?></div>
    <div id="order-product" style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('items') ?>
    </div>
    <div id="order-product" style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('billing_address') ?>
    </div>
    <div id="order-product" style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('shipping_address') ?>
    </div>
    <div id="order-product" style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('billing_method') ?>
    </div>
    <div id="order-product" style="display:<?php echo $this->getCustomerSelectorDisplay() ?>">
        <?php echo $this->getChildHtml('totals') ?>
    </div>
</form>
<script type="text/javascript">
     function show() {
          var grid = document.getElementById('product_grid');
          grid.style.display = '';
          console.log(grid);
     }
     function changeAction() {
        console.log(111);
          var form = document.getElementById('edit_form');
          form.setAttribute('action', "<?php echo $this->getUrl('*/*/save') ?>");
          form.submit();
     }
</script>
