<?php $order = $this->getOrder() ?>
<form id="quote_form" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="content-header">
        <h3 class="icon-head head-adminhtml-order"></h3>
        <h3 class="icon-head head-sales-order">Order Details of <?php echo $order->getCustomer()->getFirstname() ?></h3>
        <p class="form-buttons">
        <button id="back_order_top_button" title="Back" type="button" class="scalable back" 
        onclick="setLocation('<?php echo $this->getBackUrl() ?>')" >
        <span><span><span>Back</span></span></span></button>
            <button id="reset_order_top_button" title="Cancel" type="button" class="scalable cancel"
                onclick="deleteConfirm('Are you sure you want to cancel this order?', '<?php echo $this->getUrl('*/*/cancel') ?>')"
                ><span><span><span>Cancel</span></span></span></button>
        </p>
    </div>
    <div id="details">
        <?php echo $this->getChild('details')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="account">
        <?php echo $this->getChild('account')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="billing_address">
        <?php echo $this->getChild('billing_address')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="shipping_address">
        <?php echo $this->getChild('shipping_address')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="shipping_method">
        <?php echo $this->getChild('shipping_method')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="billing_method">
        <?php echo $this->getChild('billing_method')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="items">
        <?php echo $this->getChild('items')->setOrder($this->getOrder())->toHtml() ?>
    </div>
    <div id="totals">
        <?php echo $this->getChild('totals')->setOrder($this->getOrder())->toHtml() ?>
    </div>

</form>


