<?php $data = $this->getCustometData() ?>
<?php $groups = $this->getGroup() ?>
<div class="entry-edit">
    <button class="scalable add" style="float: right;" onclick="accountAction()" type="button"><span>Save</span></button>
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>">Account Information</h4>
    </div>
    <fieldset class="np">
        <div class="edit-form" id="order-shipping_address_fields">
            <div class="content">
                    <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                    <tr>
                                        <td class="label"><label for="Group">Group</label></td>
                                        <td class="value">
                                        <select id="customer_group" name="account[group]" class=" required-entry required-entry select">
                                            <?php foreach($groups as $key => $value): ?>
                                            <option <?php if($data->getGroupId() == $key): ?>selected <?php endif; ?>value="<?php echo $key ?>"><?php echo $value ?></option>
                                            <?php endforeach; ?>
                                    </select></td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="customer_email">Email </label></td>
                                        <td class="value">
                                        <input type='text' value="<?php echo $data->getEmail() ?>" name="account[email]"/>
                                        
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                    </div>
            </div>
        </div>
    </fieldset>
</div>