<?php  $shipping = $this->getShippingAddress(); ?>
<?php  $countries = $this->getCountry(); ?>
<div class="box-right">
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend head-shipping-address"><?php echo $this->getHeaderText() ?></h4>
        <button style="float: right;" type="button"  onclick="updateAction()"  name="billing" class="scalable task">Save</button>

     </div>
     <div class="order-save-in-address-book">
            <input name="same_billing" type="checkbox" id="order-shipping_address_save" value="1">
            <label for="order-shipping_address_save_in_address_book">Same as billing</label>
        </div>

    <fieldset class="np">

    <div class="order-address" id="order-shipping_address_fields">
        <div class="content">
                <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
        <td class="label"><label for="order-shipping_address_prefix">Prefix</label></td>
    <td class="value">
        <input id="order-shipping_address_prefix" name="order[shipping_address][prefix]" value="<?php echo $shipping->getPrefix() ?>" class=" input-text" type="text">            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_firstname">First Name<span
                                                class="required">*</span> </label></td>
    <td class="value">
        <input id="order-shipping_address_firstname" name="order[shipping_address][firstname]" value="<?php echo $shipping->getFirstname() ?>" class=" required-entry input-text required-entry" type="text">            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_middlename">Middle Name/Initial</label></td>
    <td class="value">
        <input id="order-shipping_address_middlename" name="order[shipping_address][middlename]" value="<?php echo $shipping->getMiddlename() ?>" class=" input-text" type="text">            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_lastname">Last Name <span
                                                class="required">*</span></label></td>
    <td class="value">
        <input id="order-shipping_address_lastname" name="order[shipping_address][lastname]" value="<?php echo $shipping->getLastname() ?>" class=" required-entry input-text required-entry" type="text">            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_suffix">Suffix</label></td>
    <td class="value">
        <input id="order-shipping_address_suffix" name="order[shipping_address][suffix]" value="<?php echo $shipping->getSuffix() ?>" class=" input-text" type="text">            </td>
    </tr>
<!-- <tr>
        <td class="label"><label for="order-shipping_address_company">Company</label></td>
    <td class="value">
        <input id="order-shipping_address_company" name="order[shipping_address][company]" value="" class=" input-text" type="text">            </td>
    </tr>
<tr> -->
        <td class="label"><label for="order-shipping_address_street0">Street Address <span
                                                class="required">*</span></label></td>
    <td class="value">
        <div class="multi-input"><input id="order-shipping_address_street0" name="order[shipping_address][street]" value="<?php if(is_array($shipping->getStreet()[0])){echo $shipping->getStreet()[0];} else { echo $shipping->getStreet()[0] ;}  ?>" class="input-text required-entry" type="text">
</div><!-- <div class="multi-input"><input id="order-shipping_address_street1" name="order[shipping_address][street][1]" value="" class="input-text" type="text">
</div> -->            </td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_city">City<span
                                                class="required">*</span> </label></td>
    <td class="value">
        <input id="order-shipping_address_city" name="order[shipping_address][city]" value="<?php echo $shipping->getCity() ?>" class=" required-entry input-text required-entry" type="text"></td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_country_id">Country<span
                                                class="required">*</span> </label></td>
    <td class="value">
        <select id="order-shipping_address_country_id" name="order[shipping_address][country_id]" class=" required-entry required-entry select">
        <?php foreach($countries as $contry): ?>
        <option <?php if($shipping->getCountryId() == $contry->getCountryId()): ?>selected <?php endif; ?>value="<?php echo $contry->getCountryId() ?>"><?php echo $contry->getName() ?></option>
        <?php endforeach; ?>
</select></td>
    </tr>
    <tr><td class="label"><label for="order-shipping_address_region">State/Province <span class="required" style="display: none;">*</span></label>
</td><td class="value"><input id="order-shipping_address_region" name="order[shipping_address][region]" value="<?php if($shipping['state']){echo $shipping->getState();}else{echo $shipping->getRegion(); } ?>" class="input-text" type="text">
<select id="order-shipping_address_region_id" name="order[shipping_address][region_id]" class="select" style="display:none" defaultvalue="" disabled=""><option value="">Please select</option></select>
</td></tr>
<tr>
        <td class="label"><label for="order-shipping_address_postcode">Zip/Postal Code<span
                                                class="required">*</span> </label></td>
    <td class="value">
    <input id="order-shipping_address_postcode" name="order[shipping_address][postcode]" value="<?php echo $shipping->getPostcode()  ?>" class=" required-entry input-text required-entry" type="text">
</td>
    </tr>
<tr>
        <td class="label"><label for="order-shipping_address_telephone">Telephone<span
                                                class="required">*</span> </label></td>
    <td class="value">
        <input id="order-shipping_address_telephone" name="order[shipping_address][telephone]" value="<?php echo $shipping->getTelephone() ?>" class=" required-entry input-text required-entry" type="text">            </td>
    </tr>

            </tbody>
        </table>
            </div>
            </div>
        <div class="order-save-in-address-book">
            <input name="shipping_check" type="checkbox" id="order-shipping_address_save_in_address_book" value="1">
            <label for="order-shipping_address_save_in_address_book">Save in address book</label>
        </div>
    </div>
        <div style="display: none; position: absolute; background-color: rgb(153, 153, 153); opacity: 0.8; width: 300px; height: 637px; top: 0px; left: 0px;" id="address-shipping-overlay" class="overlay"><span>Shipping address selection is not applicable</span></div>
    
    </fieldset>
</div>
</div>